### ISSUE TITLE
Gold Cab for MDX-2024101500

### ISSUE THREAD

**Issue by maurioski** [two-torial/sp2xpatcher#11]
this text is extracted from [@https://github.com/22vv0/asphyxia_plugins/releases/tag/mdx-3.0.3c](https://github.com/22vv0/asphyxia_plugins/releases/tag/mdx-3.0.3c)

`    {
        "name": "Force Cab Mode",
        "description": "",
        "gameCode": "MDX",
        "type": "number",
        "patch": {
            "dllName": "gamemdx.dll",
            "offset": 61163,
            "size": 1,
            "min": 0,
            "max": 7
        }
    }`

crd to @22vv0

**Comment by maurioski** [comment]
> What does this do exactly? I'm not a DDR player.

`The Triple Tribe 4 events do not save if the game isn't in Gold cab mode, resulting in the song notifications to appear every login. You can fix this problem by using patchers (sp2x patcher, web patcher) to force Gold cab, and letting it save your data once. Notifications will not appear on your next login anymore. This is the sp2x patch I personally use, modify your patch json file (only for 2024101500) and add this entry, enable this patch and set value to either 6 or 7. Do note that the songs only appear in Gold cab mode, unless you force unlock them by modifying the limited_ary values in data/world.ts, or if you have "unlock all songs" enabled, etc.`

**Comment by akitakedits** [comment]
If possible I'd like to make this a memory patch rather than a number patch because it doesn't make much sense.
Is there any difference between 6 and 7 being set?

**Comment by komikazui** [comment]
6 is first-generation Gold cabinets (ADE-6291, BIO2) and 7 is a new generation, mid-A3 refresh of the Gold cabinet (X10LSQ, BIO2)

**Comment by komikazui** [comment]
Also, on MDX-003, if you link up with another cabinet, it is possible to play local matching, Was first introduced in A3 as BPL BATTLE.

**Comment by akitakedits** [comment]
Thanks for the added info, will look into this now I'll just make it a Union patch.

**Comment by akitakedits** [comment]
If I sent an edited patches.json file to someone, can you confirm it works? I don't have the game set up.

**Comment by maurioski** [comment]
> If I send an edited patches.json file to someone, can you confirm it works? I don't have the game set up. Hit me up on discord.

already to help,

**Comment by akitakedits** [comment]
[MDX-670636e7_1bd9b9.json](https://github.com/user-attachments/files/17780601/MDX-670636e7_1bd9b9.json)

Let me know if there are any issues. If not I'll push it to main.

**Comment by akitakedits** [comment]
Pushed out, thank you for testing.
https://github.com/two-torial/sp2xpatcher/commit/34eba84adfe16b3b68a212b2fc3b62b7ca081394
