### ISSUE TITLE
[Request] patches for KFC-2024111901

### ISSUE THREAD

**Issue by Whynoa** [two-torial/sp2xpatcher#12]
Title. I'd like all of the timer freeze patches, please.

**Comment by scrib-bler** [comment]
You either need to provide the patches/a PR yourself, or wait. Patches can't just be magiced out of thin air the second an update hits cabs.

**Comment by Whynoa** [comment]
Doesn't work for me.... I'll wait for the official website to be updated, it usually doesn't take long.

**Comment by yxrei** [comment]
> Doesn't work for me.... I'll wait for the official website to be updated, it usually doesn't take long.

Yes, but we are also just human and do this in our free time, voluntarily. Some updates take some time.

**Comment by Whynoa** [comment]
It doesn't take long to run a python script... but ok.

**Comment by Whynoa** [comment]
Got it to work, had to use https://github.com/akitakedits/find_sp2x_patches.

**Comment by Whynoa** [comment]
Well the patcher is still missing 2024111901 patches

**Comment by Whynoa** [comment]
find_sp2x_patches runs but I can't make it work on my setup, so I'll wait for you guys to update it.
