### ISSUE TITLE
[Request] SDVX: Lock Extra Track Gauge

### ISSUE THREAD

**Issue by huantianad** [two-torial/sp2xpatcher#13]
Add a patch that prevents the Extra Track Gauge that fills after clearing a song from increasing. This would be helpful for when friend matching, since the game does not let you friend match on the extra track.

Perhaps I could take a try at this myself if nobody is interested, but wanted to put this here since I have zero experience patching SDVX :)

**Comment by akitakedits** [comment]
In fairness I believe this is a network-side issue, not a client issue.
Asphyxia ex-track doesn't work, but on proper networks it does.

**Comment by huantianad** [comment]
Wow, extrack gauge doesn't increment on Asphyxia? That's so interesting. So you're saying that this is something that can be toggled on and off network side too?

**Comment by akitakedits** [comment]
No I'm saying the plugin probably doesn't support those server calls properly.

**Comment by huantianad** [comment]
No, I'm not looking at this as an issue. I'm looking for a patch that would cause it to "break" and for the gauge to not go up on purpose.

**Comment by akitakedits** [comment]
We're not adding a patch to "break" the game so it works with the broken asphyxia plugin.
Make an issue on your plugin's repository talking about this instead, it's on their end.
