### ISSUE TITLE
[Request] LDJ-010 2024112200 patches

### ISSUE THREAD

**Issue by Whynoa** [two-torial/sp2xpatcher#14]
Please add the patches for this PC version, thanks.

**Comment by akitakedits** [comment]
Please quit making issues like this.
Support is added as soon as I get data for it.
If it's not supported it means nobody gave me the DLL.
If you want your patches, send me the DLL on Discord.

**Comment by Whynoa** [comment]
Dude, it's a simple request. But ok. What's your Discord tag?

**Comment by Whynoa** [comment]
I also need LDJ-012 2024112000 patches.

**Comment by akitakedits** [comment]
> Dude, it's a simple request. But ok. What's your Discord tag?

The way you word things make you sound really entitled, not exactly making me want to help you.
My discord is: `akitakedits`

> I also need LDJ-012 2024112000 patches.

If you have the DLL I can add support.

**Comment by akitakedits** [comment]
Those people asked for a potential new patch to be added, not pleading for support on day 1 of the version being out on cabs like you did last time.

**Comment by Whynoa** [comment]
Today is the 27th, far reach from 22. And you've supported patches day-1 in the past regularly. Why not now?

**Comment by akitakedits** [comment]
And I already said on that other issue that if people want support they can generate the json themselves using the tool I provide, or send me the DLLs

> Those people asked for a potential new patch to be added, not pleading for support on day 1 of the version being out on cabs like you did last time.

And I already said on that other issue that if people want support they can generate the json themselves using the tool I provide, or send me the DLLs



> Today is the 27th, far reach from 22. And you've supported patches day-1 in the past regularly. Why not now?

Because Konami tightened security recently, so my usual source hasn't been able to send me data quickly.

**Comment by Whynoa** [comment]
Who is your usual source?

**Comment by akitakedits** [comment]
> Who is your usual source?

Why in the world would I tell you
