### ISSUE TITLE
iidx: "QWERTY Keyboard Layout for Song Search" not needed for 31+

### ISSUE THREAD

**Issue by sp2xdev** [two-torial/sp2xpatcher#4]
Starting with iidx31, the QWERTY layout is already the default. User can go back to the old alphabetical layout by pressing a button.

**Comment by akitakedits** [comment]
Good to know! Thank you.

I took a lot of external patches when first feeding this repo and didn't double check everything.

Will remove those in a little bit.

**Comment by akitakedits** [comment]
Fixed with https://github.com/two-torial/sp2xpatcher/commit/0d2590e5e886d7b0092b6588ab11b1a9f8f9b9c5
