### ISSUE TITLE
[Request] pop'n music UniLab, Jam&Fizz

### ISSUE THREAD

**Issue by CherryDrops** [two-torial/sp2xpatcher#7]
There are no patches since 解明リドルズ, is there support?

**Comment by akitakedits** [comment]
pop'n'hax is what people tend to use, so I haven't truly bothered porting patches any further.

Anyone's free to contribute though, this is an open repo and I don't have to be the one to do it.

**Comment by CherryDrops** [comment]
I have seen the advantages of popnhax.
However, I play multiple BGames, and I think it would be nice to have a common management system using sp2xpatcher, so I made a request.
If you feel this is unnecessary, please feel free to close the issue.
Thank you very much for your response.
