### ISSUE TITLE
LDJ omnimix patch not applying "X" revision for 2024-08-26 (012)

### ISSUE THREAD

**Issue by sp2xdev** [two-torial/sp2xpatcher#8]
Expected: iidx31 boots with "J:E:X" when omnimix patch is on

Actual: game boots with J:E:A

Root cause: seems to be a bad patch. Comparing LDJ-66c58ff1_9b323c contents vs the one from BemaniPatcher:

![image](https://github.com/user-attachments/assets/93a05ff3-05b8-4454-bf7c-09fb484d7e77)

seems like the last line makes a difference.

Only 012 was verified, possible that 010 is also affected.

**Comment by akitakedits** [comment]
Interesting, I just copied mon's 1-1 but maybe I made a mistake. Will fix within a couple hours.
